### ISSUE TITLE
[BUG] csv_reader function

### ISSUE THREAD

**Issue by EverLookNeverSee** [EverLookNeverSee/ASFR#41]
Hi @moharnadreza 
csv_reader function was deleted on one of my previous pull requests, but you called it as an exposed function in your index.js file:
https://github.com/EverLookNeverSee/ASFR/blob/1b7ae38df61d04a936aa77fe0a9483825f0cb7d0/web/index.js#L91-L97

It was supposed to you create a function to read and display csv files.

**Comment by moharnadreza** [comment]
thanks @EverLookNeverSee, I took care of it in https://github.com/EverLookNeverSee/ASFR/commit/501b614f1789bd78b29d350a3c4b4009ca1d6029
